### ISSUE TITLE
Error during cell parsing

### ISSUE THREAD

**Issue by dodu94** [inr-kit/numjuggler#15]
Hello,
I have been using the numjuggler/parser.py module as an engine for parsing MCNP input files and I encountered an error while parsing the attached input:

[HCPB_TBM_1D.txt](https://github.com/inr-kit/numjuggler/files/6569604/HCPB_TBM_1D.txt)

For some reason, when reading the cells cards, some of them are not read correctly as individual but they are clustered toghether instead:
![image](https://user-images.githubusercontent.com/25747626/120180977-b9f26a00-c20c-11eb-9893-48b3d1704782.png)

I can work around that but I thought it may be useful for you to know this.

Cheers,
Davide

**Comment by travleev** [comment]
Thank you for reporting the bug. 

I think it is caused by ``&`` that is still (although after ``$``) interpreted as continuation line sentinel.

Please note that this bug is not repeated in the fork [travleev/numjuggler](https://github.com/travleev/numjuggler):
![image](https://user-images.githubusercontent.com/8748313/120469167-4da96f00-c3a2-11eb-80fb-f6d7f182061c.png)

Maybe this bug is not repeated also with the current version in this repo. Please ensure that you use the most recent version.

**Comment by dodu94** [comment]
Thank you, i will check the new version davide
