### ISSUE TITLE
Small bug in msimp module (Version 2.42a.27)

### ISSUE THREAD

**Issue by Radiation-Transport** [inr-kit/numjuggler#4]
**Bug found in --mode msimp module <<numjuggler version 2.42a.27>>**

In some cases numjuggler does not insert a dummy element composition when the MCARD number (e.g., M309) is not followed by an isotope and the related quantity.

A example is attached.

[test_msimpl.txt](https://github.com/inr-kit/numjuggler/files/3652462/test_msimpl.txt)

**Comment by travleev** [comment]
The bug is fixed in the issue4 branch. The test input file [test_msimpl_extra.txt](https://github.com/inr-kit/numjuggler/files/3656586/test_msimpl_extra.txt) contains another test cases of the material card.

Please test. If successful, I will merge the issue4 branch to the master.

To get the bugfix:

```
> cd /path/to/local/repo/numjuggler   # change to the local repo
> git pull                            # get the latest changes
> git checkout issue4                 # make the branch 'issue4' active
```

**Comment by Radiation-Transport** [comment]
**It works!** Great job and thanks for your support!
